gRust.ItemRegister("holosight")
:SetName("Holosight")
:SetDescription("The Holosight is a craftable alternative to standard weapon iron sights. Its reticle is a bright red holographic bullseye which also glows in the dark, making it the best scope for night-time combat. Thanks to its slight magnification, it can provide a greater degree of accuracy to any ranged weapon without sacrificing recoil control or close-quarter capabilities. It's especially useful if barrel attachments obscure the weapon's original sights, such as the Silencer.")
:SetStack(1)
:SetIcon("materials/items/attachments/holosight.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 12,
    "tech_trash", 1
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(125)
:SetTier(2)
:Register()

gRust.ItemRegister("simple_handmade_sight")
:SetName("Simple Handmade Sight")
:SetDescription("The Simple Handmade Sight is a makeshift alternative to a weapon's iron sights. Its reticle is simply a single post that comes to a sharp point - not too dissimilar from the German #1 reticle. This scope is particularly useful for close engagements as it provides the widest field of view out of all the scopes, but it is usually not practical at longer distances due to its negative magnification making distant targets appear smaller. Alternatively, it can be used when the weapon's iron sights are obscured by barrel attachments such as the Silencer or by the lighting caused by Fire Arrows.")
:SetStack(1)
:SetIcon("materials/items/attachments/handmade_sight.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 6
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetTier(1)
:Register()

gRust.ItemRegister("silencer")
:SetName("Silencer")
:SetDescription("The Silencer is a barrel attachment known to reduce gunfire sounds. It also removes the muzzle flash, giving you a good advantage during night without being spotted. It is quite useful against unaware enemies, and can allow you to get in extra hits before being spotted. Although the disadvantages can make short range battles go wrong. It is a good option for Bolt Action Rifles and L96s as the Silencer completely hides the bullet tracers, making the enemies confused where it came from, though it will reduce the velocity of the gun, meaning that you will need to aim a bit higher than usual to hit your opponent.")
:SetStack(1)
:SetIcon("materials/items/attachments/silencer.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 5
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(75)
:SetTier(1)
:Register()

gRust.ItemRegister("weapon_flashlight")
:SetName("Weapon Flashlight")
:SetDescription("The Flashlight is a weapon attachment, able to be attached to eligible weapons. To use it, the user presses their attachment function key (default F), and a bright cone of light will emit from underneath the barrel of their weapon. Light is useful for being able to see in the dark or blinding other players if close enough.")
:SetStack(1)
:SetIcon("materials/items/attachments/weapon_flashlight.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 3
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(75)
:SetTier(1)
:Register()

gRust.ItemRegister("8x_zoom_scope")
:SetName("8x Zoom Scope")
:SetDescription("The 8x Zoom Scope is a hand-crafted telescopic sight. Its reticle is simply a thin cross. Its magnification allows for greater precision over long ranges and extending most weapon's range, but is not ideal for close quarter engagements.")
:SetStack(1)
:SetIcon("materials/items/attachments/8xscope.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 50
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(125)
:SetTier(3)
:Register()

gRust.ItemRegister("16x_zoom_scope")
:SetName("16x Zoom Scope")
:SetDescription("The 16x Zoom Scope is a military-grade telescopic sight. Its reticle is a thin cross with bullet-drop guides. Its extreme magnification allows for precise fire over extreme distances, but its narrow field of view makes it impractical for any close quarter engagements or full-auto fire. As it's susceptible to shaking, consider using a Weapon Lasersight or Tactical Gloves in addition to this scope.")
:SetStack(1)
:SetIcon("materials/items/attachments/16xscope.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 80
)
:Register()

gRust.ItemRegister("weapon_lasersight")
:SetName("Weapon Lasersight")
:SetDescription("The Weapon Lasersight serves as a welcome attachment to any weapon, with its only hindrance being the rarity of tech trash, and the possibility of a player tracing the laser back to its user. The reduced hip spread and aim sway makes it useful for weapons at close and distant ranges alike.")
:SetStack(1)
:SetIcon("materials/items/attachments/weapon_lasersight.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 3,
    "tech_trash", 1
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(125)
:SetTier(3)
:Register()

gRust.ItemRegister("muzzle_brake")
:SetName("Muzzle Brake")
:SetDescription("The Muzzle Brake is a barrel attachment used to reduce recoil with the cost of weapon damage. It is very effective for recoils that is hard to control, like the Assault Rifle. However, the Muzzle Brake will drastically decrease the velocity of the bullets, giving you a disadvantage for long range battles. It is recommended with full-auto weapons or semi-auto weapons.")
:SetStack(1)
:SetIcon("materials/items/attachments/muzzle_brake.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 8
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(125)
:SetTier(2)
:Register()

gRust.ItemRegister("muzzle_boost")
:SetName("Muzzle Boost")
:SetDescription("The Muzzle Boost provides a greater rate of fire (and negligible recoil reduction) at the cost of less damage and velocity. The effect is most pronounced in high rate of fire, low damage weapons, such as the Custom SMG and MP5A4.")
:SetStack(1)
:SetIcon("materials/items/attachments/muzzle_boost.png")
:SetMaterial("Gun")
:AddToCategory("Attachments")
:AddToCategory("Weapons")
:SetRecipe(
    "hq_metal", 10
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(125)
:SetTier(2)
:Register()