gRust.ItemRegister("hazmat_suit")
:SetName("Hazmat Suit")
:SetDescription("The Hazmat Suit allows the wearer to travel through rad-towns and other irradiated areas safely. While it doesn't provide full protection in certain places at monuments, such as the main building at Launch Site, or the cooling tower at the Nuclear Power Plant, it offers protection from radiation poisoning at almost every other monument on the map, making it useful for exploring. The suit itself is a bright yellow color, meaning it is easy to spot from a distance.")
:SetStack(1)
:SetIcon("materials/items/clothing/hazmat.png")
:SetMaterial("Cloth")
:AddToCategory("Clothing")
:SetRecipe(
    "tarp", 5,
    "sewing_kit", 2,
    "hq_metal", 8
)
:SetCraftable(true)
:SetCraftTime(20)
:SetResearchCost(125)
:SetTier(2)
:SetAttire(
    gRust.CreateAttire(AttireType.Full)
        :SetModel("models/player/darky_m/rust/hazmat.mdl")
        :SetProjectileResistance(0.3)
        :SetMeleeResistance(0.3)
        :SetBiteResistance(0.08)
        :SetRadiationResistance(0.5)
        :SetColdResistance(0.08)
        :SetExplosiveResistance(0.05)
        :SetWaterproof(true)
)
:Register()

gRust.ItemRegister("scientist_suit")
:SetName("Scientist Suit")
:SetDescription("The Scientist Suit is worn by roaming scientists.")
:SetStack(1)
:SetIcon("materials/items/clothing/scientist.png")
:SetMaterial("Cloth")
:SetAttire(
    gRust.CreateAttire(AttireType.Full)
        :SetModel("models/player/darky_m/rust/scientist.mdl")
        :SetProjectileResistance(0.3)
        :SetMeleeResistance(0.3)
        :SetBiteResistance(0.8)
        :SetRadiationResistance(0.5)
        :SetColdResistance(0.08)
        :SetExplosiveResistance(0.05)
        :SetWaterproof(true)
)
:Register()

gRust.ItemRegister("hemp_hat")
:SetName("Hemp Hat")
:SetDescription("A hemp hat.")
:SetStack(1)
:SetIcon("materials/items/clothing/hemp_hat.png")
:SetMaterial("Cloth")
:SetAttire(
    gRust.CreateAttire(AttireType.Head)
        :SetModel("models/environment/plants/hemp.mdl")
        :SetBone("eyes")
        :SetColdResistance(0.05)
        :SetProjectileResistance(0.05)
)
:Register()

gRust.ItemRegister("coffee_can_helmet")
:SetName("Coffee Can Helmet")
:SetDescription("The coffee can helmet is a face protector that is one tier below the metal facemask, it offers good protection against physical damage to the head and costs less to craft than its older and better brother, the metal facemask.")
:SetStack(1)
:SetIcon("materials/items/clothing/coffee_can_helmet.png")
:SetMaterial("Metal")
:AddToCategory("Clothing")
:SetRecipe(
    "cloth", 15,
    "metal_fragments", 60,
    "sewing_kit", 1
)
:SetCraftable(true)
:SetCraftTime(30)
:SetResearchCost(75)
:SetTier(2)
:SetAttire(
    gRust.CreateAttire(AttireType.Head)
        :SetModel("models/attire/head/attire_coffeecanhelmet.mdl")
        :SetBone("eyes")
        :SetPosition(Vector(-4, 0, -72))
        :SetProjectileResistance(0.2) -- 0.35
        :SetMeleeResistance(0.3)
        :SetBiteResistance(0.08)
        :SetRadiationResistance(0.05)
        :SetExplosiveResistance(0.08)
)
:Register()

gRust.ItemRegister("boonie_hat")
:SetName("Boonie Hat")
:SetDescription("Equivalent stats and cost to burlap headwrap, but can be combined with the bandana.")
:SetStack(1)
:SetIcon("materials/items/clothing/boonie_hat.png")
:SetMaterial("Cloth")
:AddToCategory("Clothing")
:SetRecipe(
    "cloth", 10
)
:SetCraftable(true)
:SetCraftTime(30)
:SetAttire(
    gRust.CreateAttire(AttireType.Head)
        :SetModel("models/attire/head/boonie_hat.mdl")
        :SetBone("eyes")
        :SetPosition(Vector(-3.5, 0, 3.75))
        :SetProjectileResistance(0.15)
        :SetMeleeResistance(0.15)
        :SetBiteResistance(0.03)
        :SetRadiationResistance(0.02)
        :SetColdResistance(0.07)
)
:Register()

gRust.ItemRegister("metal_chest_plate")
:SetName("Metal Chest Plate")
:SetDescription("The metal chest plate is a versatile end-game armor used most often when roaming and raiding. Though high quality metal is often stored in abundance due to its limited use, players should begin making room for the sewing kits as this period comes into the horizon.")
:SetStack(1)
:SetIcon("materials/items/clothing/metal_chest_plate.png")
:SetMaterial("Metal")
:AddToCategory("Clothing")
:SetRecipe(
    "leather", 50,
    "hq_metal", 25,
    "sewing_kit", 8
)
:SetCraftable(true)
:SetCraftTime(45)
:SetResearchCost(500)
:SetTier(3)
:SetAttire(
    gRust.CreateAttire(AttireType.Chest)
        :SetModel("models/attire/body/attire_metalchestplate.mdl")
        :SetBone("chest")
        :SetPosition(Vector(0, -0.2, -2.8))
        :SetAngles(Angle(0, 90, 0))
        :SetProjectileResistance(0.2) -- 0.35
        :SetMeleeResistance(0.4)
        :SetBiteResistance(0.08)
        :SetRadiationResistance(0.05)
        :SetExplosiveResistance(0.08)
)
:Register()