gRust.ItemRegister("apple")
:SetName("Apple")
:SetDescription("The apple is a food that gives the player food and water. Unlike most other foods the apple gives lots more hydration when consumed. Can be found in food crates and medical crates.")
:SetStack(10)
:SetIcon("materials/items/consumable/apple.png")
:SetMaterial("Wood")
:SetCalories(30)
:SetHydration(15)
:SetInstantHealth(2)
:Register()

gRust.ItemRegister("can_of_beans")
:SetName("Can of Beans")
:SetDescription("Beans found as loot. Eating it provides a small boost to health, hunger, and thirst.")
:SetStack(10)
:SetIcon("materials/items/consumable/can_of_beans.png")
:SetMaterial("Metal")
:SetCalories(100)
:SetHydration(25)
:SetInstantHealth(4)
:SetOnConsumed(function(pl, inventory, index)
    pl:AddItem("empty_can_of_beans")
end)
:Register()

gRust.ItemRegister("can_of_tuna")
:SetName("Can of Tuna")
:SetDescription("Chunked tuna found as loot. Eating it provides a small boost to health, hunger, and thirst.")
:SetStack(10)
:SetIcon("materials/items/consumable/can_of_tuna.png")
:SetMaterial("Metal")
:SetCalories(50)
:SetHydration(15)
:SetInstantHealth(2)
:SetOnConsumed(function(pl, inventory, index)
    pl:AddItem("empty_tuna_can")
end)
:Register()

gRust.ItemRegister("chocolate_bar")
:SetName("Chocolate Bar")
:SetDescription("Chocolate Bar found as loot. Eating it provides a small boost to health, hunger, and thirst.")
:SetStack(10)
:SetIcon("materials/items/consumable/chocolate_bar.png")
:SetMaterial("Paper")
:SetCalories(100)
:SetHydration(1)
:SetInstantHealth(2)
:Register()

gRust.ItemRegister("granola_bar")
:SetName("Granola Bar")
:SetDescription("Granola Bar found as loot. Eating it provides a small boost to health, hunger, and thirst.")
:SetStack(10)
:SetIcon("materials/items/consumable/granola_bar.png")
:SetMaterial("Paper")
:SetCalories(60)
:SetInstantHealth(5)
:Register()

gRust.ItemRegister("pickles")
:SetName("Pickles")
:SetDescription("Pickles are edible food. However, you have a chance of getting your hunger and hydration decreased (you'll hear a vomit sound). It is recommended you save up pickles to feed horses, use as a bait for fish traps or compost for fertilizers.")
:SetStack(10)
:SetIcon("materials/items/consumable/pickles.png")
:SetMaterial("Wood")
:SetCalories(50)
:SetHydration(20)
:SetInstantHealth(5)
:SetOnConsumed(function(pl, inventory, index)
    if (math.random(1, 3) == 1) then
        pl:EmitSound(string.format("player/vomit_%i.wav", math.random(1, 2)))
        pl:SetHealth(pl:Health() - 5)
        pl:SetCalories(pl:GetCalories() - 80)
        pl:SetHydration(pl:GetHydration() - 40)

        return true
    end
end)
:Register()