gRust.ItemRegister("wood")
:SetName("Wood")
:SetDescription("Wood. Collected from trees and used in many crafting recipes. It's also needed to cook in camp-fires.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/wood.mdl")
:SetIcon("materials/items/resources/wood.png")
:SetMaterial("Wood")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("stones")
:SetName("Stones")
:SetDescription("Harvested from rocks using tools, basic building material.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/stone.mdl")
:SetIcon("materials/items/resources/stone.png")
:SetMaterial("Stone")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("metal_ore")
:SetName("Metal Ore")
:SetDescription("Metal ore can be smelted into metal fragments through a furnace which is used to craft most of the tools, structures, items and weaponry throughout the game and is vital to have during most of the time being.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/metal_ore.mdl")
:SetIcon("materials/items/resources/metal_ore.png")
:SetMaterial("Stone")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("hq_metal_ore")
:SetName("High Quality Metal Ore")
:SetDescription("A rock containing High Quality Metal. Can be smelted in a furnace.")
:SetStack(1000)
:SetIcon("materials/items/resources/hqmetal_ore.png")
:SetMaterial("Stone")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("sulfur_ore")
:SetName("Sulfur Ore")
:SetDescription("Sulfur ore is a resource found in Sulfur nodes. Smelting sulfur ore in any furnace will give sulfur, an ingredient in crafting gunpowder.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/sulfur_ore.mdl")
:SetIcon("materials/items/resources/sulfur_ore.png")
:SetMaterial("Stone")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("metal_fragments")
:SetName("Metal Fragments")
:SetDescription("Metal Fragments. Smelted from Metal Ore, used in lots of different crafting recipes.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/metalfragments.mdl")
:SetIcon("materials/items/resources/metal_fragments.png")
:SetMaterial("Metal")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("hq_metal")
:SetName("High Quality Metal")
:SetDescription("High Quality Metal is considered as a rare resource used for crafting metal items such as armor, doors, weapons and more. High Quality Metal is often used as the 'top-tier' when constructing or upgrading building blocks.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/hqmetal.mdl")
:SetIcon("materials/items/resources/hqmetal.png")
:SetMaterial("Metal")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("scrap")
:SetName("Scrap")
:SetDescription("Resource mainly used for researching items into blueprints at workbenches or going down the tech tree, which allows for targeting certain items you want to acquire. It's also a type of currency, used for trading various items at the Scientist Outpost and the Bandit Camp. As such, Scrap is very valuable and essential at any point in the game.")
:SetStack(1000)
:SetAbsoluteMax(20000)
:SetModel("models/darky_m/rust/worldmodels/scrappile.mdl")
:SetIcon("materials/items/resources/scrap.png")
:SetMaterial("Metal")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("crude_oil")
:SetName("Crude Oil")
:SetDescription("Raw Oil out of the ground, must be refined in a refinery to be used. Can be found in barrels scattered across the map.")
:SetStack(500)
:SetIcon("materials/items/resources/crude_oil.png")
:SetMaterial("Stone")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("low_grade_fuel")
:SetName("Low Grade Fuel")
:SetDescription("Low Grade Fuel is a resource made from Animal Fat and Cloth. It is required early game to make furnaces and mid game for Syringes. There are three ways to get this, hunting animals (or to a lesser effect, humans) and crafting it, refining crude oil at a monument or personal refinery, and finding it in oil barrels (or to a lesser effect in mine carts).")
:SetStack(500)
:SetIcon("materials/items/resources/low_grade_fuel.png")
:SetMaterial("Cloth")
:AddToCategory("Resources")
:SetRecipe(
    "animal_fat", 3,
    "cloth", 1
)
:SetCraftable(true)
:SetCraftAmount(4)
:SetCraftTime(5)
:Register()

gRust.ItemRegister("animal_fat")
:SetName("Animal Fat")
:SetDescription("Fat is a good package for biological energy, making it quite an effective fuel source. It can be taken from any animal, including humans.")
:SetStack(1000)
:SetIcon("materials/items/resources/animal_fat.png")
:SetMaterial("Wood")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("cloth")
:SetName("Cloth")
:SetDescription("Cloth is a basic resource that has several means of being harvested. Most commonly it is farmed with hemp and hemp seeds, but can be gathered from animals and even cacti with the appropriate tools. It is used primarily for clothing, and the refining of low grade when combined with animal fat. To make cloth gathering a trivial task, the proper use of planters is recommended.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/cloth.mdl")
:SetIcon("materials/items/resources/cloth.png")
:SetMaterial("Cloth")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("charcoal")
:SetName("Charcoal")
:SetDescription("Charcoal is the byproduct of wood when used for smelting in a campfire or furnace. It is used in conjunction with sulfur to craft gunpowder, a key ingredient for ammunition and explosives. Though it may be tempting to throw charcoal away, large quantities will be required in later stages of the game. Keep it if you can.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/charcoal.mdl")
:SetIcon("materials/items/resources/charcoal.png")
:SetMaterial("Charcoal")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("bone_fragments")
:SetName("Bone Fragments")
:SetDescription("Bone fragments are obtainable from any corpse and used in armor and tools.")
:SetStack(1000)
:SetIcon("materials/items/resources/bone_fragments.png")
:SetMaterial("Wood")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("gun_powder")
:SetName("Gun Powder")
:SetDescription("Gunpowder is a resource created by combining smelted sulfur and charcoal. It is used for multiple things from rockets, grenades, ammunition, and even land mines. As this is used almost exclusively for PvP purposes, this is a much sought after resource and should be protected and seized at every opportunity.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/gunpowder.mdl")
:SetIcon("materials/items/resources/gunpowder.png")
:SetMaterial("Wood")
:AddToCategory("Resources")
:SetRecipe(
    "charcoal", 30,
    "sulfur", 20
)
:SetCraftable(true)
:SetCraftAmount(10)
:SetCraftTime(2)
:SetTier(1)
:Register()

gRust.ItemRegister("sulfur")
:SetName("Sulfur")
:SetDescription("One of the most valuable and sought after resources in rust, sulfur is useful to almost all players (with the exception of freshspawns) due to it being required to craft gunpowder, a resource necessary to create ammo as well as any explosive. It can be found in its ore form in sulfur nodes, identifiable by their distinct yellow colouring. This then needs to be smelted in a furnace in order to obtain its purified form seen here.")
:SetStack(1000)
:SetModel("models/darky_m/rust/worldmodels/sulphur.mdl")
:SetIcon("materials/items/resources/sulfur.png")
:SetMaterial("Wood")
:AddToCategory("Resources")
:Register()

gRust.ItemRegister("explosives")
:SetName("Explosives")
:SetDescription("Explosives are used in more powerful raiding devices. They cannot be used on their own, only as an ingredient.")
:SetStack(100)
:SetModel("models/darky_m/rust/worldmodels/explosives.mdl")
:SetIcon("materials/items/resources/explosives.png")
:SetMaterial("Wood")
:AddToCategory("Resources")
:SetRecipe(
    "gun_powder", 50,
    "low_grade_fuel", 3,
    "sulfur", 10,
    "metal_fragments", 10
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(5)
:SetResearchCost(500)
:SetTier(3)
:Register()

gRust.ItemRegister("tech_trash")
:SetName("Tech Trash")
:SetDescription("Tech Trash is an essential component in Timed Explosive Charges and weapon attachments. Tech Trash can be gained via military crates or the recycler.")
:SetStack(50)
:SetModel("models/darky_m/rust/worldmodels/techTrash.mdl")
:SetIcon("materials/items/resources/tech_trash.png")
:SetMaterial("Wood")
:AddToCategory("Resources")
:SetRecycleScrap(20)
:SetRecipe(
    "hq_metal", 2
)
:Register()

gRust.ItemRegister("rope")
:SetName("Rope")
:SetDescription("Rope is quite common component used in many items like wooden armor, satchel charges, ladders and shotgun traps. Because of that it remains relatively useful throughout the whole game. It can be often found in barrels alongside sewing kits which can be recycled for even more rope.")
:SetStack(50)
:SetFormat("%sft")
:SetModel("models/darky_m/rust/worldmodels/rope.mdl")
:SetIcon("materials/items/resources/rope.png")
:SetMaterial("Cloth")
:AddToCategory("Resources")
:SetRecipe(
    "cloth", 30
)
:Register()

gRust.ItemRegister("sewing_kit")
:SetName("Sewing Kit")
:SetDescription("Sewing Kits are highly valued by mid to high tier players for their use in both roadsign and metal Armour.")
:SetStack(50)
:SetModel("models/darky_m/rust/worldmodels/sewingKit.mdl")
:SetIcon("materials/items/resources/sewing_kit.png")
:SetMaterial("Cloth")
:AddToCategory("Resources")
:SetRecipe(
    "cloth", 20,
    "rope", 3
)
:SetCraftable(true)
:SetCraftTime(30)
:SetResearchCost(75)
:SetTier(3)
:Register()

gRust.ItemRegister("tarp")
:SetName("Tarp")
:SetDescription("Tarps are used for the crafting of planter boxes, and water catchers. They can also be recycled for 50x cloth each. These are very common and can prove to be a good source of cloth.")
:SetStack(20)
:SetModel("models/darky_m/rust/worldmodels/tarp.mdl")
:SetIcon("materials/items/resources/tarp.png")
:SetMaterial("Cloth")
:AddToCategory("Resources")
:SetRecipe(
    "cloth", 100
)
:Register()

gRust.ItemRegister("leather")
:SetName("Leather")
:SetDescription("One of the resources commonly acquired through harvesting most animals. It's necessary for the making of mid and end tier armors, needed by every Rust player. Acquired in abundance mainly through the harvesting of bears and wolves.")
:SetStack(1000)
:SetIcon("materials/items/resources/leather.png")
:SetMaterial("Cloth")
:AddToCategory("Resources")
:SetRecipe(
    "cloth", 5
)
:SetCraftable(true)
:Register()

gRust.ItemRegister("cctv_camera")
:SetName("CCTV Camera")
:SetDescription("A CCTV Camera can be placed down to capture video footage and sound when powered and paired with a Computer Station.")
:SetStack(64)
:SetModel("models/darky_m/rust/worldmodels/cctv.mdl")
:SetIcon("materials/items/resources/cctv_camera.png")
:SetMaterial("Gun")
:AddToCategory("Resources")
:SetRecipe(
    "tech_trash", 4,
    "hq_metal", 4
)
:Register()

gRust.ItemRegister("targeting_computer")
:SetName("Targeting Computer")
:SetDescription("Used for crafting auto turrets, or recycling a large amounts of scrap.")
:SetStack(64)
:SetModel("models/darky_m/rust/worldmodels/targComp.mdl")
:SetIcon("materials/items/resources/targeting_computer.png")
:SetMaterial("Gun")
:AddToCategory("Resources")
:SetRecipe(
    "tech_trash", 6,
    "hq_metal", 2,
    "metal_fragments", 100
)
:Register()