gRust.ItemRegister("rock")
:SetName("Rock")
:SetDescription("A Rock. The most basic melee weapon and gathering tool.")
:SetIcon("materials/items/tools/rock.png")
:SetStack(1)
:SetCondition(true)
:SetWeapon("rust_rock")
:SetModel("models/weapons/darky_m/rust/w_rock.mdl")
:SetMaterial("Stone")
:AddToCategory("Tools")
:SetRecipe(
    "stones", 10
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(5)
:Register()

gRust.ItemRegister("stone_hatchet")
:SetName("Stone Hatchet")
:SetDescription("The Stone Hatchet is a primitive, early game tool used for collecting wood and flesh. It is available to craft, costing only wood and stones. Players starting out may find great use of the Stone Hatchet along with the Stone Pickaxe to aid in their farming endeavors. Although it is much less efficient than the Hatchet or Salvaged Axe, it is still used commonly due to its low barrier of entry- not costing any processed materials which require a furnace.")
:SetIcon("materials/items/tools/stone_hatchet.png")
:SetStack(1)
:SetCondition(true)
:SetWeapon("rust_stonehatchet")
:SetModel("models/weapons/darky_m/rust/w_stone_hatchet.mdl")
:SetMaterial("Stone")
:AddToCategory("Tools")
:SetRecipe(
    "wood", 200,
    "stones", 100
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(15)
:Register()

gRust.ItemRegister("stone_pickaxe")
:SetName("Stone Pickaxe")
:SetDescription("Primitive tool used for harvesting Stone, Metal ore and Sulfur ore. Can also be used to harvest animals due to its relatively high harvest rate, and contrary to popular belief, it is more efficient than the stone hatchet.")
:SetIcon("materials/items/tools/stone_pickaxe.png")
:SetStack(1)
:SetCondition(true)
:SetWeapon("rust_stonepickaxe")
:SetModel("models/weapons/darky_m/rust/w_stone_pickaxe.mdl")
:SetMaterial("Stone")
:AddToCategory("Tools")
:SetRecipe(
    "wood", 200,
    "stones", 100
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(15)
:Register()

gRust.ItemRegister("building_plan")
:SetName("Building Plan")
:SetDescription("The Building Plan is used to create weak twig structures at the cost of a nominal amount of wood. These twigs may be upgraded with a Hammer if the player has the resources to do so. Players may not build in zones in which there is a tool cupboard that they are not authorized on. Additionally, players may not build in certain areas of the map (such as near a radtown). Otherwise, players may build anywhere of their choosing.")
:SetIcon("materials/items/tools/building_plan.png")
:SetStack(1)
:SetWeapon("rust_buildingplan")
:SetModel("models/weapons/darky_m/rust/w_buildingplan.mdl")
:SetMaterial("Paper")
:AddToCategory("Construction")
:AddToCategory("Tools")
:SetRecipe(
    "wood", 20
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(15)
:Register()

gRust.ItemRegister("hammer")
:SetName("Hammer")
:SetDescription("A tool used for rotating, repairing, and upgrading parts of structures. It can also be used to pick up certain deployable items.")
:SetIcon("materials/items/tools/hammer.png")
:SetStack(1)
:SetWeapon("rust_hammer")
:SetModel("models/weapons/darky_m/rust/w_hammer.mdl")
:SetMaterial("Wood")
:AddToCategory("Tools")
:SetRecipe(
    "wood", 100
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(15)
:Register()

gRust.ItemRegister("hatchet")
:SetName("Hatchet")
:SetDescription("An improved gathering rate is offset by a significantly longer gather speed, though it is nonetheless considered far superior to its stone counterpart. It is as efficient as the salvaged ice pick but just a bit slower.")
:SetIcon("materials/items/tools/hatchet.png")
:SetStack(1)
:SetCondition(true)
:SetWeapon("rust_hatchet")
:SetModel("models/weapons/darky_m/rust/w_iron_hatchet.mdl")
:SetMaterial("Metal")
:AddToCategory("Tools")
:SetRecipe(
    "wood", 100,
    "metal_fragments", 75
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(75)
:SetTier(1)
:Register()

gRust.ItemRegister("pickaxe")
:SetName("Pickaxe")
:SetDescription("This tool is a must-have for any gRust player. It is the most efficient tool when gathering wood and harvesting animals. Relatively cheap and durable, this tool should be what you aim for in the early stages of the game.")
:SetIcon("materials/items/tools/pickaxe.png")
:SetStack(1)
:SetCondition(true)
:SetWeapon("rust_pickaxe")
:SetModel("models/weapons/darky_m/rust/w_iron_pickaxe.mdl")
:SetMaterial("Metal")
:AddToCategory("Tools")
:SetRecipe(
    "wood", 100,
    "metal_fragments", 125
)
:SetCraftable(true)
:SetCraftAmount(1)
:SetCraftTime(30)
:SetResearchCost(75)
:SetTier(1)
:Register()

-- gRust.ItemRegister("wire_tool")
-- :SetName("Wire Tool")
-- :SetDescription("A tool used to make connections between electrical objects. To use the Wire Tool, aim at an electrical object to highlight the available inputs and outputs (connections). Press the LMB to attach wires to these connections (wires can clip through any item). To disconnect a wired connection, highlight the connection and hold RMB. Wired connections can be disconnected with RMB while simultaneously holding a wire to then be connected. Electrical components will automatically grey out connections that cannot be paired based on their type (input vs output). Hold R to view wire color wheel.")
-- :SetIcon("materials/items/tools/wire_tool.png")
-- :SetStack(1)
-- :SetWeapon("rust_wiretool")
-- :SetMaterial("Metal")
-- :AddToCategory("Tools")
-- :SetRecipe(
--     "hq_metal", 2
-- )
-- :SetCraftable(true)
-- :SetCraftAmount(1)
-- :SetCraftTime(1)
-- :SetTier(1)
-- :Register()

gRust.ItemRegister("green_keycard")
:SetName("Green Keycard")
:SetDescription("The Green Keycard is a required object used to open doors with a glowing green keycard lock.")
:SetIcon("materials/items/keycards/green_keycard.png")
:SetStack(1)
:SetCondition(true)
:SetWeapon("rust_keycard")
:SetModel("models/darky_m/rust/puzzle/access_card.mdl")
:SetMaterial("Metal")
:AddToCategory("Tools")
:Register()

gRust.ItemRegister("blue_keycard")
:SetName("Blue Keycard")
:SetDescription("The Blue Keycard is a required object used to open doors with a glowing blue keycard lock.")
:SetIcon("materials/items/keycards/blue_keycard.png")
:SetStack(1)
:SetCondition(true)
:SetWeapon("rust_keycard")
-- :SetModel("models/darky_m/rust/puzzle/access_card.mdl")
:SetMaterial("Metal")
:AddToCategory("Tools")
:Register()

gRust.ItemRegister("red_keycard")
:SetName("Red Keycard")
:SetDescription("The Red Keycard is a required object used to open doors with a glowing red keycard lock.")
:SetIcon("materials/items/keycards/red_keycard.png")
:SetStack(1)
:SetCondition(true)
:SetWeapon("rust_keycard")
-- :SetModel("models/darky_m/rust/puzzle/access_card.mdl")
:SetMaterial("Metal")
:AddToCategory("Tools")
:Register()