local Icons = {}

function gRust.CreateIcon(name, dir)
    local icon = Material(dir, "noclamp smooth mips")
    Icons[name] = icon
end

function gRust.GetIcon(name)
    return Icons[name] or Icons["default"]
end

gRust.CreateIcon("default", "icons/close.png")
gRust.CreateIcon("close", "icons/close.png")
gRust.CreateIcon("health", "icons/health.png")
gRust.CreateIcon("hunger", "icons/hunger.png")
gRust.CreateIcon("water", "icons/water.png")
gRust.CreateIcon("bleeding", "icons/bleeding.png")
gRust.CreateIcon("wet", "icons/wet.png")
gRust.CreateIcon("drop", "icons/drop.png")
gRust.CreateIcon("circle", "icons/circle.png")
gRust.CreateIcon("enter", "icons/enter.png")
gRust.CreateIcon("exit", "icons/exit.png")
gRust.CreateIcon("servers", "icons/servers.png")
gRust.CreateIcon("construction", "icons/construction.png")
gRust.CreateIcon("extinguish", "icons/extinguish.png")
gRust.CreateIcon("dots", "icons/dots.png")
gRust.CreateIcon("tools", "icons/tools.png")
gRust.CreateIcon("weapon", "icons/weapon.png")
gRust.CreateIcon("favorite.active", "icons/favourite_active.png")
gRust.CreateIcon("favorite.inactive", "icons/favorite_inactive.png")
gRust.CreateIcon("medical", "icons/medical.png")
gRust.CreateIcon("ammo", "icons/ammo.png")
gRust.CreateIcon("electric", "icons/electric.png")
gRust.CreateIcon("fun", "icons/fun_alt.png")
gRust.CreateIcon("give", "icons/give.png")
gRust.CreateIcon("pickup", "icons/pickup.png")
gRust.CreateIcon("stab", "icons/stab.png")
gRust.CreateIcon("bullet", "icons/bullet.png")
gRust.CreateIcon("explosion", "icons/explosion.png")
gRust.CreateIcon("freezing", "icons/freezing.png")
gRust.CreateIcon("radiation", "icons/radiation.png")
gRust.CreateIcon("bite", "icons/bite.png")
gRust.CreateIcon("time", "icons/time.png")
gRust.CreateIcon("add", "icons/add.png")
gRust.CreateIcon("subtract", "icons/subtract.png")
gRust.CreateIcon("forward", "icons/forward.png")
gRust.CreateIcon("maximum", "icons/maximum.png")
gRust.CreateIcon("stopwatch", "icons/stopwatch.png")
gRust.CreateIcon("authorize", "icons/authorize.png")
gRust.CreateIcon("gear", "icons/gear.png")
gRust.CreateIcon("safezone", "icons/safe_zone.png")
gRust.CreateIcon("open", "icons/open.png")
gRust.CreateIcon("open_door", "icons/open_door.png")
gRust.CreateIcon("power", "icons/power.png")
gRust.CreateIcon("banana", "icons/traps.png")
gRust.CreateIcon("lock", "icons/lock.png")
gRust.CreateIcon("info", "icons/info.png")
gRust.CreateIcon("boosts", "icons/boosts.png")
gRust.CreateIcon("eat", "icons/eat.png")
gRust.CreateIcon("alert", "icons/alert2.png")
gRust.CreateIcon("pistolbullet", "icons/pistol_bullet.png")
gRust.CreateIcon("riflebullet", "icons/rifle_bullet.png")
gRust.CreateIcon("crosshair", "icons/crosshair.png")
gRust.CreateIcon("demolish", "icons/demolish.png")
gRust.CreateIcon("rotate", "icons/rotate.png")
gRust.CreateIcon("unlock", "icons/unlock.png")
gRust.CreateIcon("knock", "icons/knock.png")
gRust.CreateIcon("key", "icons/key.png")
gRust.CreateIcon("changecode", "icons/change_code.png")
gRust.CreateIcon("skull", "icons/skull.png")
gRust.CreateIcon("loot", "icons/player_loot.png")
gRust.CreateIcon("clear", "icons/clear_list.png")
gRust.CreateIcon("deauthorize", "icons/deauthorize.png")
gRust.CreateIcon("store", "icons/store.png")
gRust.CreateIcon("broadcast", "icons/broadcast.png")
gRust.CreateIcon("vending", "icons/vending.png")
gRust.CreateIcon("target", "icons/target.png")
gRust.CreateIcon("voice", "icons/voice.png")
gRust.CreateIcon("broken", "icons/broken.png")
gRust.CreateIcon("friends", "icons/friends.png")

-- Building
gRust.CreateIcon("build.foundation", "icons/build/foundation.png")
gRust.CreateIcon("build.foundation_steps", "icons/build/foundation_steps.png")
gRust.CreateIcon("build.triangle_foundation", "icons/build/triangle_foundation.png")
gRust.CreateIcon("build.floor", "icons/build/floor.png")
gRust.CreateIcon("build.floor_frame", "icons/build/floor_frame.png")
gRust.CreateIcon("build.floor_triangle", "icons/build/floor_triangle.png")
gRust.CreateIcon("build.stairs", "icons/build/stairs.png")
gRust.CreateIcon("build.stairs_u", "icons/build/stairs_u.png")
gRust.CreateIcon("build.stairs_l", "icons/build/stairs_l.png")
gRust.CreateIcon("build.doorframe", "icons/build/doorframe.png")
gRust.CreateIcon("build.wall", "icons/build/wall.png")
gRust.CreateIcon("build.wall_low", "icons/build/wall_low.png")
gRust.CreateIcon("build.wall_frame", "icons/build/wall_frame.png")
gRust.CreateIcon("build.wall_window", "icons/build/wall_window.png")
gRust.CreateIcon("build.wall_half", "icons/build/wall_half.png")
gRust.CreateIcon("build.roof", "icons/build/roof.png")
gRust.CreateIcon("level_wood", "icons/level_wood.png")
gRust.CreateIcon("level_stone", "icons/level_stone.png")
gRust.CreateIcon("level_metal", "icons/level_metal.png")
gRust.CreateIcon("level_top", "icons/level_top.png")

-- Tech Tree
gRust.CreateIcon("techtree.close", "icons/techtree_close.png")
gRust.CreateIcon("techtree.locked", "icons/techtree_locked.png")
gRust.CreateIcon("techtree.unlocked", "icons/techtree_unlocked.png")

-- Casino
gRust.CreateIcon("casino.1", "icons/casino/1.png")
gRust.CreateIcon("casino.3", "icons/casino/3.png")
gRust.CreateIcon("casino.5", "icons/casino/5.png")
gRust.CreateIcon("casino.10", "icons/casino/10.png")
gRust.CreateIcon("casino.20", "icons/casino/20.png")

-- Map
gRust.CreateIcon("map.player", "icons/map/player.png")
gRust.CreateIcon("map.death", "icons/map/death.png")
gRust.CreateIcon("map.waypoint", "icons/map/waypoint.png")
gRust.CreateIcon("map.vendingmachine", "icons/map/vendingmachine.png")