_G["METERS_TO_UNITS"] = 51.4285714
_G["UNITS_TO_METERS"] = 1 / _G["METERS_TO_UNITS"]
_G["DEGREES_TO_RADIANS"] = math.pi / 180
_G["RADIANS_TO_DEGREES"] = 180 / math.pi
_G["MAX_REACH_RANGE"] = 256
_G["MAX_REACH_RANGE_SQR"] = _G["MAX_REACH_RANGE"] * _G["MAX_REACH_RANGE"]